In [4]:
import pandas as pd

# Load files
hr_df = pd.read_excel(r"C:\Users\vamsi\Desktop\Datawarehousing_assignment\HR_Dataset_Dirty.xlsx")
finance_df = pd.read_excel(r"C:\Users\vamsi\Desktop\Datawarehousing_assignment\Finance_Dataset_Dirty.xlsx")
ops_df = pd.read_excel(r"C:\Users\vamsi\Desktop\Datawarehousing_assignment\Operations_Dataset_Dirty.xlsx")

display(hr_df.head())
display(finance_df.head())
display(ops_df.head())

print("HR Columns:", hr_df.columns.tolist())
print("Finance Columns:", finance_df.columns.tolist())
print("Operations Columns:", ops_df.columns.tolist())

,EmployeeID,Name,Department,Gender,DateOfJoining,ManagerID,Salary,Status
0,1001,Employee 1001,IT,M,2018-10-09,2003,94088,Resigned
1,1002,Employee 1002,It,F,2017-03-06,2003,91466,Resigned
2,1003,Employee 1003,NaN,F,2022-03-02,2002,52179,Resigned
3,1004,Employee 1004,IT,M,2016-01-03,2003,-10000,Resigned
4,1005,Employee 1005,HR,M,15-01-2018,2002,115497,Active

   EmployeeID ExpenseType  ExpenseAmount ExpenseDate  ApprovedBy
0        1016       Meals         -50.75  2023-05-21      2002.0
1        9999    Supplies         936.61  2023-08-13      2002.0
2        1013     Travell        1052.43  2023-02-19      2001.0
3        1004      Travel         545.61  2025-12-31      2003.0
4        1001       Meals         645.39  2023-02-03         NaN

   Department         ProcessName  DowntimeHours ProcessDate       Location
0       Legal  Server Maintenance           5.09  2023-09-01      Warehouse
1     Finance      Security Audit           5.47  2023-02-08   Remot Site A
2  Operations                 NaN           2.69  2023-07-21      Warehouse
3          IT     Inventory Check            NaN  2023-01-31  Remote Site A
4     Finance         Data Backup           7.66         NaN  Remote Site A

HR Columns: ['EmployeeID', 'Name', 'Department', 'Gender', 'DateOfJoining', 'ManagerID', 'Salary', 'Status']
Finance Columns: ['EmployeeID', 'ExpenseType', 'ExpenseAmount', 'ExpenseDate', 'ApprovedBy']
Operations Columns: ['Department', 'ProcessName', 'DowntimeHours', 'ProcessDate', 'Location']